openapi: "3.0.0"
info:
  description: Набор методов для учёта предприятия
  version: 1.0.0
  title: RestApi
servers:
  - url: /api
    description: Base URL for the API
paths:
  /api/store/turnover:
    post:
      summary: Добавить фильтр для отчета по домену
      operationId: src.api.routes.store.get_turnovers
      requestBody:
        description: DTO модель для фильтрации
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreTurnoverDTO'
      responses:
        200:
          description: Фильтр успешно добавлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /api/prototype/{entity}:
    post:
      summary: Добавить фильтр для отчета по домену
      operationId: src.api.routes.prototype.get_by_entity
      parameters:
        - name: entity
          in: path
          description: Тип юнита для прототипа
          required: true
          schema:
            type: string
            enum:
              - recipes
              - nomenclatures
              - nomenclature_groups
              - measurement_units
              - store_transaction
              - storehouse
      requestBody:
        description: DTO модель для фильтрации
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Filters'
      responses:
        200:
          description: Фильтр успешно добавлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
components:
  schemas:
    StoreTurnoverDTO:
      type: object
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/FilterItem'
        start_time:
          type: integer
        end_time:
          type: integer
    FilterItem:
      type: object
      properties:
        key:
          type: string
        value:
          oneOf:
            - type: string
            - type: number
            - type: boolean
            - type: array
        operation:
          type: string
          enum:
            - EQUAL
            - LIKE
            - BETWEEN
    Filters:
      type: array
      items:
        $ref: '#/components/schemas/FilterItem'
